/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x56, 0x46, 0x06, 0x0E, 0xB0, 0x92, 0xA4, 0xB5}

#define VIAL_ENCODER_KEYCODE_DELAY 10
#define VIAL_ENCODER_DEFAULT { KC_MS_WH_UP, KC_MS_WH_DOWN, KC_VOLD, KC_VOLU, KC_MS_WH_LEFT, KC_MS_WH_RIGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS }
